import path from 'node:path';
import { readdir } from 'node:fs/promises';
import { ensureDir, escapeHtml, formatAuDate, fromRoot, readJson, writeJson, writeText } from './utils.mjs';
import { campaignSummary } from './engine.mjs';

export async function buildCampaignPreview(config) {
  const directory=fromRoot('_content','blog');const items=[];
  try{for(const file of (await readdir(directory)).filter(file=>file.endsWith('.json'))){items.push(await readJson(path.join(directory,file)));}}catch(error){if(error.code!=='ENOENT')throw error;}
  items.sort((a,b)=>a.date.localeCompare(b.date));
  const cards=(await Promise.all(items.map(async item=>{
    const brief=await readJson(fromRoot('data','daily-briefs',`${item.date}.json`));
    return `<article class="card"><picture><source srcset="../../${item.creative.variants.instagram.webp}" type="image/webp"><img src="../../${item.creative.variants.instagram.png}" alt="${escapeHtml(item.hero_image_alt)}" width="1080" height="1350"></picture><div class="copy"><div class="meta">Day ${item.campaign_day} · ${formatAuDate(item.date)} · Promotion ${item.promotion_score}/100</div><h2>${escapeHtml(item.title)}</h2><p><strong>${escapeHtml(item.category)}</strong> · ${escapeHtml(item.creative.variants.instagram.width)} × ${escapeHtml(item.creative.variants.instagram.height)}</p><details><summary>Instagram caption</summary><p>${escapeHtml(item.instagram_caption).replace(/\n/g,'<br>')}</p></details><details><summary>Creative brief</summary><pre>${escapeHtml(JSON.stringify(brief,null,2))}</pre></details><details><summary>Article preview</summary><pre>${escapeHtml(item.article_markdown)}</pre></details></div></article>`;
  }))).join('');
  const summary=await campaignSummary(config);
  const html=`<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Run Lighter 14-day campaign preview</title><style>:root{--oat:#f3efe5;--paper:#fbf8f1;--moss:#344137;--ink:#29312c;--muted:#697068;--sage:#718069;--line:rgba(52,65,55,.16)}*{box-sizing:border-box}body{margin:0;background:var(--oat);color:var(--ink);font:15px/1.55 Arial,sans-serif}.wrap{width:min(1280px,calc(100% - 32px));margin:auto;padding:50px 0}h1{font-size:clamp(38px,6vw,70px);letter-spacing:-.04em;margin:0}.intro{color:var(--muted);max-width:760px}.summary{display:flex;gap:12px;flex-wrap:wrap;margin:28px 0}.summary span{padding:9px 12px;background:var(--paper);border:1px solid var(--line);border-radius:999px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:24px}.card{display:grid;grid-template-columns:minmax(220px,.72fr) 1fr;overflow:hidden;background:var(--paper);border:1px solid var(--line);border-radius:24px}.card img{display:block;width:100%;height:100%;object-fit:cover}.copy{padding:25px;min-width:0}.meta{color:var(--sage);font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.06em}h2{font-size:27px;line-height:1.1}details{border-top:1px solid var(--line);padding:12px 0}summary{cursor:pointer;font-weight:700}pre{white-space:pre-wrap;max-height:420px;overflow:auto;background:var(--oat);padding:12px;border-radius:10px;font-size:11px}@media(max-width:980px){.grid{grid-template-columns:1fr}}@media(max-width:620px){.card{grid-template-columns:1fr}.card img{aspect-ratio:4/5}}</style></head><body><main class="wrap"><p>RUN / LIGHTER</p><h1>14-day automated content preview</h1><p class="intro">All content is in draft. Live website and Instagram publishing remain disabled until the owner intentionally enables both controls.</p><div class="summary"><span>${items.length} packages</span><span>${summary.promotion_candidates} promotion candidates</span><span>${new Set(items.map(item=>item.creative.variants.instagram)).size} rendered creatives</span></div><div class="grid">${cards}</div></main></body></html>`;
  await ensureDir(fromRoot('preview','14-day'));await writeText(fromRoot('preview','14-day','index.html'),html);await writeJson(fromRoot('preview','14-day','summary.json'),summary);return {items:items.length,path:'preview/14-day/index.html',summary};
}
